### PR TITLE
feat: Socks5 proxy support

### PR DESCRIPTION
**Pull request by go-compile**
Reopen of https://github.com/linkwarden/linkwarden/pull/150 on latest base.

## Added Features
Added socks5 proxy support for pdf and png archiving (including the title fetch).
PDF margin ENV options.

### New environment variables
```ts
      ARCHIVER_PROXY?: string;
      ARCHIVER_PROXY_USERNAME?: string;
      ARCHIVER_PROXY_PASSWORD?: string;
      ARCHIVER_PROXY_BYPASS?: string;
      
      ARCHIVER_PDF_MARGIN_TOP?: string;
      ARCHIVER_PDF_MARGIN_BOTTOM?: string;
```

## Limitations
One limitation is the remote favicons being loaded via the gstatic API, this is not proxied.
A environment variable i.e. `DISABLED_REMOTE_FAVICON=true` would be the simplest fix for this, with the icons being replaced with a placeholder image instead.

### CODE REVIEW

**Comment by daniel31x13** [comment]
Thanks! can you just please replace npm with yarn?

**Comment by go-compile** [comment]
Sure. I don't typically use yarn but I suppose you just need me to run `yarn install node-fetch socks-proxy-agent` and commit all changes?

**Comment by daniel31x13** [comment]
The yarn.lock file is using package registries from npm instead of yarn so yeah you need to install the packages using yarn instead.

**Comment by go-compile** [comment]
Done 👍

**Comment by daniel31x13** [comment]
thank you!

**Pull request merged**
