### PR TITLE
Add Single file archive method.

### LINKED ISSUE #192: SingleFile archive and/or arbitrary files linked to an entry
**Is your feature request related to a problem? Please describe.**
My problem is twofold (might be overloading this issue but didn't want to spam). Firstly the PDF extractor isn't perfect (although it's pretty good) - some deferred images in pages didn't get picked up. Also sometimes I want to save an interactive page (although not sure any tool will do that super reliably). Secondly, some pages I want to keep are originally not HTML (e.g. PDF, or video), and it doesn't look like the conversion process works for at least PDFs (understandable that the PDF converter would find PDF->PDF a confusing request).

**Describe the solution you'd like**
Pages to be processed with SingleFile or similar and that to be added to an entry - and/or - the ability to upload arbitrary files (consider Calibre-Web's functionality to upload various formats of a book).

### PR DESCRIPTION
**Pull request by rutkai**
Add the option to archive links as Single file html:
image

Fixes #192.

TODO:
* [x] Add documentation PR: linkwarden/docs#27

### CODE REVIEW

**Comment by daniel31x13** [comment]
Thank you for this PR! Gonna merge things soon.

**Comment by daniel31x13** [comment]
Hello I just took a look at this and noticed it's only functional using docker, there are many people who are taking the manual installation and this prevents them from using this feature.

Also thanks to Gildas (SingleFile maintainer), he just ported single-file-cli to node in the latest release ([v2.0.3](https://github.com/gildas-lormeau/single-file-cli/releases/tag/v2.0.3)) per this comment:
https://github.com/gildas-lormeau/SingleFile/discussions/1048#discussioncomment-8828886

This should make things much easier. That being said, let me know if you need any help.

P.S. just outlined a high-level architecture of the project over here:
https://github.com/linkwarden/linkwarden/blob/dev/ARCHITECTURE.md

**Comment by daniel31x13** [comment]
@rutkai Thanks! Sorry for missing that.
I'm finalizing the changes at the moment and will be merging this PR soon!

**Comment by daniel31x13** [comment]
Hey I wasn't able to run this on a dummy server. Well, the problem was single-file.
Don't wanna put any pressure but can you implement a AIO solution (per [this](https://github.com/linkwarden/linkwarden/pull/525#issuecomment-2005233842)) so that there's no need to install single-file separately? It's not critical but really helps if you could.

**Comment by rutkai** [comment]
Hey, okay, sure, but what is the problem exactly? My thoughts on this:

* The lack of documentation on how to install single-file? This part should be the concern of single-file-cli documentation. I managed to get it working on my dev machine, it is possible that it needs `deno` installed.
* How about using the single-file docker container (a sample included in the `docker-compose.yml` file)? That's the point of using containers: you don't need to mess with dependencies and it's a completely lightweight abstraction. I'm running everything in containers at home.

Shall I give you a hand sometime? Discord? Or Discourse? Or... anything that is faster than commenting on a PR? :D

**Comment by daniel31x13** [comment]
Here's the whole discussion: https://github.com/gildas-lormeau/single-file-cli/discussions/73#discussioncomment-8949692

The reason I'm trying to avoid to go for a docker-only approach is for the users who are opting for the manual installation.

And yes Discord's a better place to continue this conversation, thanks! :)

**Pull request merged**
