### PR TITLE
Use official nodejs base image, slim down container image

### PR DESCRIPTION
**Pull request by peschmae**
- Playwright 1.35 supports debian 11 (bullseye), for debian 12 (bookworm) support, playwright needs to be updated
- Ensure all apt & yarn caches are cleaned in the same step they are used (slims down image)
- Image uses a lot less steps now, and slimmed down form ~4GB to 2.5GB

This makes the container image easier to manage, as it has less steps, and updating just relies on updating the upstream images.

I'm already running this image, and it works fine including generating the screenshots & pdf for websites.

### CODE REVIEW

**Comment by peschmae** [comment]
It also makes building the images faster and will help with #166

**Comment by daniel31x13** [comment]
Merging it, thanks.

**Comment by daniel31x13** [comment]
@peschmae Hey just tested this on an M1 Mac and noticed it crashes when I start archiving a webpage, do you know what could be causing the problem?

**Comment by peschmae** [comment]
Oh, I only tested it on amd64 hardware, as I thought I read that arm64 isn't supported

But I'll give this a try tomorrow, as I have access to an M1 at work and check it out.

The previous image worked on M1, I assume?

**Comment by daniel31x13** [comment]
Sorry for the late reply, looks like Playwright isn't working properly on macOS, which is unusual given that Docker should work consistently across all platforms. Just tested is and it looks like the previous image didn't capture the webpages as well.

**Comment by peschmae** [comment]
There seem to be a few tickets for playwright and arm64/m1, for example: https://github.com/microsoft/playwright/issues/11150

I'll try switching playwright to firefox in the docker container, to see if it works then.

**Comment by peschmae** [comment]
I've created a issue to follow up on this: #175

**Pull request merged**
