### PR TITLE
Add German Translation

### PR DESCRIPTION
**Pull request by Green-Kite**
Add German translation

### CODE REVIEW

**Review by nklamann — APPROVED** [review]
Looks good to me

**Comment by daniel31x13** [comment]
Hi there, big thanks for your contribution.

I added/removed some fields from the main `en` locale file, could you please make another PR fixing them? For now I'll be merging this one.

**Comment by Green-Kite** [comment]
@nklamann I've updated the german locale file in #809 could you approve it again?

**Comment by nklamann** [comment]
Coming Monday

**Pull request merged**
