### PR TITLE
Bootstrap icons

### PR DESCRIPTION
**Pull request by YeeJiaWei**

### CODE REVIEW

**Comment by daniel31x13** [comment]
Changed base from `linkwarden:dev` to `linkwarden:bootstrap-icons`.
Ping me when you're done.
Thanks!

**Comment by YeeJiaWei** [comment]
i have complete update to bootstrap icons.

However, in this commit ([e9acb54](https://github.com/linkwarden/linkwarden/pull/349/commits/e9acb548bfd6e92bde8b0c1afec7dfe40b9f9b05)), i have forced to remove some component (no referenced) / font awesome icons directly (without replacement), since i have no idea where to find the component showing.

If you can help to point out, thats help a lot

**Comment by daniel31x13** [comment]
Oh yeah they were unused components from the past.

By being “forced” you mean at build time right?

**Comment by daniel31x13** [comment]
Thanks a lot for this, you did a lot!

**Comment by daniel31x13** [comment]
I'll be merging everything to main right when everything is ready.

**Pull request merged**
