### PR TITLE
Reduces the size of the Docker image 

### PR DESCRIPTION
**Pull request by fredbcode**
and improves adherence to best practices
 2.3GB vs 4.13 Gb

### CODE REVIEW

**Comment by fredbcode** [comment]
My goal was to maintain the original structure and ease of maintenance

**Comment by fredbcode** [comment]
Run as non root-user !! for upgrade change the rights to 1161 !!

 volumes:
      - data_warden:/data/**data**

**Comment by fredbcode** [comment]
Do you have or needs a ci for auto build images ?

**Comment by daniel31x13** [comment]
Thank you for your contribution but this is a duplicate of #688.
Sorry for the inconvenience.

**Pull request closed without merging**
